  ## default connection pool
  spring:
    datasource:
      hikari:
        connectionTimeout: 20000
        maximumPoolSize: 5
      ## PostgreSQL
      url: jdbc:postgresql://localhost:5432/example?options=-c%20TimeZone=UTC
      username: postgres
      password: testpass
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            time_zone: UTC
      hibernate.ddl-auto: update
      hibernate.show-sql: true
  #  autoconfigure:
  #    exclude:
  #      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


  jwt:
    private.key: classpath:private_key.pem
    public.key: classpath:test-pub.pem

  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
    override-with-generic-response: false

  server:
    port: 9090
